sudo: required
services:
  - docker

before_install:
  - docker build -t jameszhujian/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jameszhujian/react-test npm run test -- --coverage

after_success:
  - docker build -t jameszj/multi-client:v5 ./client
  - docker build -t jameszj/multi-nginx ./nginx
  - docker build -t jameszj/multi-server ./server
  - docker build -t jameszj/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jameszj/multi-client:v5
  - docker push jameszj/multi-nginx
  - docker push jameszj/multi-server
  - docker push jameszj/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket_name: "elasticbeanstalk-us-east-2-313110838466"
#   bucket_path: "docker-multi"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
